version: 2
sources:
  - name: public
    schema: public
    tables:
      - name: fact_mobility_weather
        columns:
          - name: city
            tests: [not_null]
          - name: observed_at
            tests: [not_null]

